### ISSUE TITLE
Ground is bright white

### ISSUE THREAD

**Issue by Ono-Sendai** [scenevr/triage#10]
![image](https://cloud.githubusercontent.com/assets/30285/13558253/f3448c82-e3f7-11e5-89e2-9d5d7a1db262.png)

**Comment by bnolan** [comment]
This was a problem with the CORS config of the s3 bucket we're using for assets. Fixed!

**Comment by Ono-Sendai** [comment]
Is this fix deployed? still getting on https://client.scenevr.com/wss/grid.scenevr.com/scenes/12

**Comment by bnolan** [comment]
Okay, I'll take a look this evening.

On Thu, Mar 10, 2016 at 1:36 PM, Ono-Sendai <notifications@github.com>
wrote:

> Is this fix deployed? still getting on
> https://client.scenevr.com/wss/grid.scenevr.com/scenes/12
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scenevr/triage/issues/10#issuecomment-194589267>.
>



-- 
Regards,
Ben Nolan

http://bennolan.com/

skype: bennolan
cell: +64 21 770 662
