### ISSUE TITLE
[Editor] Why are we reinventing the wheel with the Scene VR editor?

### ISSUE THREAD

**Issue by HeadClot** [scenevr/triage#35]
OK,
So I mean no offense with this. But why are we reinventing the wheel with SceneVR's Editor? We could use a existing editor / Engine like Atomic Game Engine or Godot Engine 2. There are plenty of capable  open source 3D editors out there that we can use with SceneVR to build levels / Scenes for the web.

I think it might be a waste of resources to Invest into a bespoke editor for SceneVR when there are already allot of capable editors out there that we can use for free. Just write an exporter for the editor / Engine. In addition to this the two engines I mentioned are being actively enhanced by their  communities. So we would not need to worry about them being abandoned. Either way. My 2 cents.

https://github.com/AtomicGameEngine/AtomicGameEngine <- MIT Licensed
https://github.com/godotengine/godot <- MIT Licensed

**Comment by bnolan** [comment]
Heya, the primary difference with the SceneVR editor is that it is browser based. Going further down the track, we'll have multiuser simultaneous editing. Being able to edit scenes without downloading external software is a win in itself. :)
